openapi: 3.0.1
info:
  title: AnimalHouse.CodeFirst.Server
  description: A simple example ASP.NET Core Web API
  contact:
    name: Serhii Prostakov
    url: https://twitter.com/prostakov
    email: serhii.prostakov@propellminds.ai
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: '24.0'
paths:
  /api/v24/Animals:
    get:
      tags:
        - Animals
      summary: GetAllAnimals
      description: Gets all animals that are currently in storage
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  oneOf:
                    - $ref: '#/components/schemas/AnimalHouse.Common.Models.Animals.Bird'
                    - $ref: '#/components/schemas/AnimalHouse.Common.Models.Animals.Fish'
                    - $ref: '#/components/schemas/AnimalHouse.Common.Models.Animals.Mammal'
                    - $ref: '#/components/schemas/AnimalHouse.Common.Models.Animals.Reptile'
        '400':
          description: Invalid tag value
    post:
      tags:
        - Animals
      summary: CreateNewAnimal
      description: "Animals can be created\r\n\r\nSample request:\r\n            \r\n    POST /Todo\r\n    {\r\n       \"id\": 1,\r\n       \"name\": \"Item #1\",\r\n       \"isComplete\": true\r\n    }"
      requestBody:
        description: Animal to create
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/AnimalHouse.Common.Models.Animals.Bird'
                - $ref: '#/components/schemas/AnimalHouse.Common.Models.Animals.Fish'
                - $ref: '#/components/schemas/AnimalHouse.Common.Models.Animals.Mammal'
                - $ref: '#/components/schemas/AnimalHouse.Common.Models.Animals.Reptile'
      responses:
        '201':
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/AnimalHouse.Common.Models.Animals.Bird'
                  - $ref: '#/components/schemas/AnimalHouse.Common.Models.Animals.Fish'
                  - $ref: '#/components/schemas/AnimalHouse.Common.Models.Animals.Mammal'
                  - $ref: '#/components/schemas/AnimalHouse.Common.Models.Animals.Reptile'
        '400':
          description: Request error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
    put:
      tags:
        - Animals
      summary: UpdateAnimal
      description: Animals can be updated
      requestBody:
        description: Animal to update
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/AnimalHouse.Common.Models.Animals.Bird'
                - $ref: '#/components/schemas/AnimalHouse.Common.Models.Animals.Fish'
                - $ref: '#/components/schemas/AnimalHouse.Common.Models.Animals.Mammal'
                - $ref: '#/components/schemas/AnimalHouse.Common.Models.Animals.Reptile'
      responses:
        '204':
          description: Successful operation
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/AnimalHouse.Common.Models.Animals.Bird'
                  - $ref: '#/components/schemas/AnimalHouse.Common.Models.Animals.Fish'
                  - $ref: '#/components/schemas/AnimalHouse.Common.Models.Animals.Mammal'
                  - $ref: '#/components/schemas/AnimalHouse.Common.Models.Animals.Reptile'
        '400':
          description: Request error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnimalHouse.CodeFirst.Server.Responses.ErrorApiResponse'
        '404':
          description: Not found error
          content:
            application/json:
              schema:
                type: string
  /api/v24/Animals/tags:
    get:
      tags:
        - Animals
      summary: FindAnimalsByTags
      description: 'Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.'
      parameters:
        - name: tags
          in: query
          description: Tags to filter by
          required: true
          schema:
            type: array
            items:
              type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  oneOf:
                    - $ref: '#/components/schemas/AnimalHouse.Common.Models.Animals.Bird'
                    - $ref: '#/components/schemas/AnimalHouse.Common.Models.Animals.Fish'
                    - $ref: '#/components/schemas/AnimalHouse.Common.Models.Animals.Mammal'
                    - $ref: '#/components/schemas/AnimalHouse.Common.Models.Animals.Reptile'
        '400':
          description: Invalid tag value
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
  '/api/v24/Animals/{id}':
    delete:
      tags:
        - Animals
      summary: DeleteAnimal
      description: Animals can be deleted
      parameters:
        - name: id
          in: query
          description: Id of animal to delete
          schema:
            type: string
            format: uuid
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Successful operation
        '400':
          description: Request error
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/AnimalHouse.CodeFirst.Server.Responses.ErrorApiResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/AnimalHouse.CodeFirst.Server.Responses.ErrorApiResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/AnimalHouse.CodeFirst.Server.Responses.ErrorApiResponse'
        '404':
          description: Not found error
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
  /api/v24/Subscriptions:
    put:
      tags:
        - Subscriptions
      summary: UpdateSubscription
      description: Subscriptions can be created and updated
      requestBody:
        description: Subscription to create or update
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnimalHouse.Common.Models.Subscription'
      responses:
        '204':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnimalHouse.Common.Models.Subscription'
        '400':
          description: Request error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnimalHouse.CodeFirst.Server.Responses.ErrorApiResponse'
  '/api/v24/Subscriptions/{id}':
    delete:
      tags:
        - Subscriptions
      summary: DeleteSubscription
      description: Subscriptions can be deleted
      parameters:
        - name: id
          in: query
          description: Id of subscription to delete
          schema:
            type: string
            format: uuid
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Successful operation
        '400':
          description: Request error
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/AnimalHouse.CodeFirst.Server.Responses.ErrorApiResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/AnimalHouse.CodeFirst.Server.Responses.ErrorApiResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/AnimalHouse.CodeFirst.Server.Responses.ErrorApiResponse'
        '404':
          description: Not found error
          content:
            text/plain:
              schema:
                type: string
            application/json:
              schema:
                type: string
            text/json:
              schema:
                type: string
components:
  schemas:
    AnimalHouse.CodeFirst.Server.Responses.ErrorApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
          nullable: true
        errors:
          type: object
          additionalProperties:
            type: string
          nullable: true
      additionalProperties: false
    AnimalHouse.Common.Models.Animal:
      required:
        - discriminator
      type: object
      properties:
        discriminator:
          type: string
        id:
          type: string
          format: uuid
        name:
          type: string
          nullable: true
        createdAt:
          type: string
          format: date-time
        tags:
          type: array
          items:
            type: string
          nullable: true
      additionalProperties: false
      discriminator:
        propertyName: discriminator
        mapping:
          Bird: '#/components/schemas/AnimalHouse.Common.Models.Animals.Bird'
          Fish: '#/components/schemas/AnimalHouse.Common.Models.Animals.Fish'
          Mammal: '#/components/schemas/AnimalHouse.Common.Models.Animals.Mammal'
          Reptile: '#/components/schemas/AnimalHouse.Common.Models.Animals.Reptile'
    AnimalHouse.Common.Models.Animals.Bird:
      type: object
      allOf:
        - $ref: '#/components/schemas/AnimalHouse.Common.Models.Animal'
      properties:
        birdType:
          $ref: '#/components/schemas/AnimalHouse.Common.Models.Animals.BirdType'
      additionalProperties: false
    AnimalHouse.Common.Models.Animals.BirdType:
      enum:
        - None
        - Parrot
        - Peacock
      type: string
    AnimalHouse.Common.Models.Animals.Fish:
      type: object
      allOf:
        - $ref: '#/components/schemas/AnimalHouse.Common.Models.Animal'
      properties:
        fishType:
          $ref: '#/components/schemas/AnimalHouse.Common.Models.Animals.FishType'
      additionalProperties: false
    AnimalHouse.Common.Models.Animals.FishType:
      enum:
        - None
        - SwordFish
        - ClownFish
      type: string
    AnimalHouse.Common.Models.Animals.Mammal:
      type: object
      allOf:
        - $ref: '#/components/schemas/AnimalHouse.Common.Models.Animal'
      properties:
        mammalType:
          $ref: '#/components/schemas/AnimalHouse.Common.Models.Animals.MammalType'
      additionalProperties: false
    AnimalHouse.Common.Models.Animals.MammalType:
      enum:
        - None
        - Cat
        - Dog
      type: string
    AnimalHouse.Common.Models.Animals.Reptile:
      type: object
      allOf:
        - $ref: '#/components/schemas/AnimalHouse.Common.Models.Animal'
      properties:
        reptileType:
          $ref: '#/components/schemas/AnimalHouse.Common.Models.Animals.ReptileType'
      additionalProperties: false
    AnimalHouse.Common.Models.Animals.ReptileType:
      enum:
        - None
        - Lizard
        - Turtle
      type: string
    AnimalHouse.Common.Models.Subscription:
      type: object
      properties:
        id:
          type: string
          format: uuid
        callbackUrl:
          type: string
          nullable: true
        callbackToken:
          type: string
          nullable: true
      additionalProperties: false
    Microsoft.AspNetCore.Mvc.ProblemDetails:
      type: object
      properties:
        type:
          type: string
          nullable: true
        title:
          type: string
          nullable: true
        status:
          type: integer
          format: int32
          nullable: true
        detail:
          type: string
          nullable: true
        instance:
          type: string
          nullable: true
      additionalProperties: { }
  securitySchemes:
    Bearer:
      type: http
      description: JWT Authorization header using the Bearer scheme.
      scheme: bearer
security:
  - Bearer: [ ]